import assert from 'node:assert/strict';
import {newGame,applyPlan,parseCommand,playerPlan,derive,undo,validateImport} from '../dist/engine.js';
let now=1800000000000;Date.now=()=>now;
function fixture(){const s=newGame();for(const n of [2,4,12,16,22,31,43,45])applyPlan(s,playerPlan({number:String(n),first:n===22?'Mason':`Player${n}`,team:'home',aliases:[]},s));applyPlan(s,parseCommand('Starters are 2,4,12,16 and 43',s));applyPlan(s,parseCommand('Start game',s));return s;}
const run=(s,raw)=>{const plan=parseCommand(raw,s);applyPlan(s,plan,raw);return derive(s);};
const player=(d,n)=>Object.values(d.players).find(p=>p.number===String(n));
const s=fixture();now+=3600000;assert.equal(derive(s).clock.seconds,480);assert.equal(player(derive(s),43).minutes,0);assert.equal(derive(s).clock.running,false);
run(s,'12 passes to 43 and 43 makes a two');let d=run(s,'43 out, Mason in, 4 out, 31 in');assert.equal(d.lineups.home.size,5);assert(!player(d,43).onCourt);assert(player(d,22).onCourt);assert(!player(d,4).onCourt);assert(player(d,31).onCourt);assert.equal(d.score.home,2);assert.equal(player(d,12).stats.ast,1);assert.equal(d.timeline.filter(e=>e.awaitingClock).length,7);
d=run(s,"now it's q2 3:43");assert.equal(d.clock.period,2);assert.equal(d.clock.seconds,223);assert.equal(d.timeline.filter(e=>e.awaitingClock).length,0);assert.equal(player(d,43).minutes,737);assert.equal(player(d,22).minutes,0);assert.equal(Object.values(d.players).reduce((n,p)=>n+p.minutes,0),737*5);assert(d.timeline.filter(e=>['PLAYER_IN','PLAYER_OUT'].includes(e.type)).every(e=>e.period===2&&e.clock===223));assert.equal(d.timeline.find(e=>e.type==='PASS').clock,234);assert.equal(d.timeline.find(e=>e.type==='SHOT').clock,469);assert(d.timeline.find(e=>e.type==='SHOT').estimatedTime);
now+=500000;assert.equal(derive(s).clock.seconds,223);d=run(s,'Now it is Q2 3:00');assert.equal(player(d,22).minutes,43);assert.equal(player(d,43).minutes,737);undo(s);assert.equal(derive(s).clock.seconds,223);undo(s);d=derive(s);assert.equal(d.clock.period,1);assert.equal(d.timeline.filter(e=>e.awaitingClock).length,7);run(s,'Now it is Q2 3:43');assert.equal(derive(validateImport(JSON.parse(JSON.stringify(s)))).clock.seconds,223);
const t=fixture();d=run(t,'12 to 43, 43 makes a three, 43 out, Mason in, 4 out, 31 in, now its Q2 3:43');assert.equal(d.score.home,3);assert.equal(d.lineups.home.size,5);assert.equal(player(d,43).minutes,737);assert.equal(player(d,22).minutes,0);assert.equal(d.timeline.filter(e=>e.awaitingClock).length,0);
run(t,'22 makes a layup');run(t,'now its Q2 3:00');d=run(t,'now its Q2 2:00');assert.equal(player(d,22).minutes,103);assert.equal(d.timeline.find(e=>e.type==='SHOT'&&e.value===3).clock,469);assert.equal(d.timeline.find(e=>e.type==='SHOT'&&e.value===2).clock,180);
for(const phrase of ['43 and 4 out, Mason and 31 in','Sub Mason for 43 and 31 for 4','Take 43 out and put Mason in, take 4 out and put 31 in']){const g=fixture();const x=run(g,phrase);assert.equal(x.lineups.home.size,5,phrase);assert(player(x,22).onCourt,phrase);assert(player(x,31).onCourt,phrase);assert(!player(x,43).onCourt,phrase);assert(!player(x,4).onCourt,phrase);}
const delayed=fixture();run(delayed,'43 shoots the three');run(delayed,'now its Q2 3:43');d=run(delayed,'airball');assert.equal(d.totals.home.fga,1);assert.equal(d.timeline.find(e=>e.type==='SHOT').period,2);
console.log('PASS frozen clock, trailing and separate time checkpoints, batch retiming, player-minute conservation, immediate multiple substitutions, undo and persistence');
