import assert from 'node:assert/strict';
import {newGame,playerPlan,applyPlan,parseCommand,derive,commit} from '../dist/engine.js';
function fixture(){const s=newGame();for(const n of [12,16,43,45,22,31])applyPlan(s,playerPlan({number:''+n,first:'Player'+n,last:'',team:'home',aliases:[]},s));commit(s,[{type:'STARTERS',team:'home',players:derive(s).roster.slice(0,5).map(p=>p.id)}]);applyPlan(s,parseCommand('Tip off',s));return s;}
const say=(s,t)=>{const p=parseCommand(t,s);assert(!p.choices?.length,t);applyPlan(s,p,t);};
for(const [shot,outcome,pts] of [['43 A3','he scored',3],['43 A2','she missed',0],['43 shoots A3','he missed',0]]){const s=fixture();say(s,shot);assert.equal(derive(s).totals.home.fga,0);say(s,outcome);assert.equal(derive(s).totals.home.fga,1);assert.equal(derive(s).score.home,pts);}
for(const alias of ['opp','opponet','opponent','enemy','other team']){const s=fixture();say(s,alias);say(s,'they stole the ball');say(s,'they scored');assert.equal(derive(s).totals.away.stl,1,alias);assert.equal(derive(s).score.away,2,alias);say(s,alias+' A3');say(s,'they missed');assert.equal(derive(s).totals.away.threeA,1,alias);}
{const s=fixture();say(s,'enemy A3');say(s,'12 gets the rebound');assert.equal(derive(s).totals.away.threeA,1);assert.equal(derive(s).totals.home.dreb,1);}
{const s=fixture(),before=JSON.stringify(s);assert.throws(()=>say(s,'31 A3'),/bench/);assert.throws(()=>say(s,'31 scored a two'),/bench/);assert.equal(JSON.stringify(s),before);assert.throws(()=>say(s,'12 passes to 31'),/bench/);say(s,'43 out, 31 in');say(s,'31 A2');say(s,'he scored');assert.equal(derive(s).score.home,2);assert.throws(()=>say(s,'43 steal'),/bench/);}
for(const phrase of ['moving onto the 2 quarter','moiving onto the 2 quarter','moving on to the second quarter','going to quarter 2']){const s=fixture();say(s,'43 made a three');say(s,phrase);const d=derive(s);assert.equal(d.clock.period,2,phrase);assert.equal(d.clock.seconds,480);assert.equal(d.clock.running,false);assert.equal(d.lineups.home.size,5);assert.equal(d.periodTotals[1].score.home,3);assert.equal(d.players[d.roster[0].id].minutes,480);say(s,'moving onto the 3 quarter');assert.equal(derive(s).clock.period,3);say(s,'moving onto the 4 quarter');assert.equal(derive(s).clock.period,4);}
console.log('PASS A2/A3 delayed outcomes, opponent aliases and context, inferred rebound, bench rejection, substitutions and quarter transitions');
