import assert from 'node:assert/strict';import {newGame,derive,applyPlan,parseCommand,playerPlan,commit,undo,validateImport} from '../dist/engine.js';
const say=(s,t)=>{const p=parseCommand(t,s);applyPlan(s,p,t);return derive(s);};
function fixture(){const s=newGame();for(const n of [2,7,9,12,14,23,43])applyPlan(s,playerPlan({number:''+n,first:'P'+n,team:'home'},s));commit(s,[{type:'STARTERS',team:'home',players:derive(s).roster.filter(p=>[2,7,9,23,43].includes(+p.number)).map(p=>p.id)}]);say(s,'Tip off');return s;}
{const s=fixture();for(let i=0;i<12;i++)say(s,'7 steal');let d=say(s,'6:00');const plays=d.timeline.filter(e=>e.type==='STAT');assert.deepEqual(plays.map(e=>e.clock),Array.from({length:12},(_,i)=>470-i*10));assert(plays.every(e=>e.estimatedTime));assert.equal(d.totals.home.stl,12);assert.equal(d.players[d.roster[0].id].minutes,120);undo(s);assert(derive(s).timeline.filter(e=>e.type==='STAT').every(e=>e.awaitingClock));say(s,'6:00');assert.equal(derive(validateImport(JSON.parse(JSON.stringify(s)))).totals.home.stl,12);}
{const s=fixture();say(s,'7 steal');say(s,'12 for 7');say(s,'12 made a two');let d=say(s,'6:00');const sub=d.timeline.filter(e=>['PLAYER_IN','PLAYER_OUT'].includes(e.type));assert(sub.every(e=>e.clock===400));assert.equal(d.players[d.roster.find(p=>p.number==='12').id].minutes,40);assert.equal(d.players[d.roster.find(p=>p.number==='7').id].minutes,80);assert.equal(Object.values(d.players).reduce((a,p)=>a+p.minutes,0),600);say(s,'No, that sub was at 6:50');d=derive(s);assert.equal(s.clock.seconds,360);assert.equal(d.players[d.roster.find(p=>p.number==='12').id].minutes,50);assert(d.timeline.filter(e=>['PLAYER_IN','PLAYER_OUT'].includes(e.type)).every(e=>e.clock===410&&!e.estimatedTime));}
{const s=fixture();say(s,'7 passes to 9, 9 shoots a two and scores');const d=say(s,'6:00');const shot=d.timeline.find(e=>e.type==='SHOT'),ast=d.timeline.find(e=>e.autoAssist);assert.equal(shot.clock,360);assert.equal(ast.clock,shot.clock);assert.equal(d.timeline.find(e=>e.type==='PASS').clock,420);}
{const s=fixture();say(s,'Clock 0:30');say(s,'7 steal');say(s,'7 made a two');let d=say(s,'Q2 7:30');const plays=d.timeline.filter(e=>['STAT','SHOT'].includes(e.type));assert.deepEqual(plays.map(e=>[e.period,e.clock]),[[1,0],[2,450]]);assert.equal(Object.values(d.players).reduce((a,p)=>a+p.minutes,0),510*5);}
{const s=fixture();say(s,'Whistle');say(s,'12 for 7');let d=say(s,'Clock 6:00');assert(d.timeline.filter(e=>['PLAYER_IN','PLAYER_OUT'].includes(e.type)).every(e=>e.clock===480&&!e.estimatedTime));}
{const s=fixture();say(s,'7 steal');const d=say(s,'Timeout us at 6:00, 12 for 7');assert(d.timeline.filter(e=>['PLAYER_IN','PLAYER_OUT','TEAM_TIMEOUT'].includes(e.type)).every(e=>e.clock===360));}
console.log('PASS 12 plays at ten-second intervals, grouped substitutions and player minutes, shared assist timestamps, historical correction, undo/reload, quarter boundaries and exact dead-ball times');
