import {authRoute,sessionUser} from './auth.js';
// Bundled static assets and the shared basketball engine are inserted by the build.
import {assets,engine} from './generated.js';
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const cleanText=(v,max=100)=>typeof v==='string'&&v.trim().length>0&&v.trim().length<=max;
function validGame(s){if(!s||!cleanText(s.id,100)||!Array.isArray(s.transactions)||s.transactions.length>15000)throw Error('Invalid game backup.');if(!s.clock||!Number.isInteger(s.clock.period)||s.clock.period<1||s.clock.period>32||!Number.isFinite(s.clock.seconds)||s.clock.seconds<0||s.clock.seconds>3600)throw Error('Invalid clock.');for(const t of s.transactions){if(!Array.isArray(t.events))throw Error('Invalid ledger.');for(const e of t.events){if(e.period<1||e.period>32||e.clock>3600)throw Error('Invalid event time.');if(e.type==='CONFIG'){const a=e.settings;if(!a||!cleanText(a.home)||!cleanText(a.away)||!Number.isInteger(a.periods)||a.periods<1||a.periods>12||!Number.isFinite(a.length)||a.length<60||a.length>3600||!Number.isFinite(a.overtime)||a.overtime<60||a.overtime>1200)throw Error('Invalid game rules.');}}}engine.validateImport(s);if(s.meta){if(s.meta.date&&!/^\d{4}-\d{2}-\d{2}$/.test(s.meta.date))throw Error('Use a valid date.');if(s.meta.startTime&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(s.meta.startTime))throw Error('Use a valid start time.');}return s;}
export default {async fetch(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/')){const name=url.pathname==='/'?'index.html':url.pathname.slice(1),asset=assets[name];if(!asset)return new Response('Not found',{status:404});const bytes=Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0));return new Response(request.method==='HEAD'?null:bytes,{headers:{'content-type':asset.type,'cache-control':'no-cache','x-content-type-options':'nosniff'}});}
if(!env.DB)return json({error:'Game storage is temporarily unavailable.'},503);if(request.method!=='GET'&&((request.headers.get('origin')&&request.headers.get('origin')!==url.origin)||request.headers.get('sec-fetch-site')==='cross-site'))return json({error:'Invalid request origin.'},403);
let account;try{if(url.pathname.startsWith('/api/auth/'))return await authRoute(request,env.DB);account=await sessionUser(request,env.DB);}catch(e){console.error('Account service',e.message);return json({error:'Account service is temporarily unavailable.'},503);}if(!account)return json({error:'Sign in to load your games.'},401);const owner=account.id;if(request.headers.get('x-courtside-account')&&request.headers.get('x-courtside-account')!==owner)return json({error:'The signed-in account changed. Reload this page.'},401);
try{if(request.method==='GET'&&url.pathname==='/api/library'){const results=await env.DB.batch([env.DB.prepare('SELECT id,name,team_name AS teamName,created_at AS createdAt FROM collections WHERE owner = ? ORDER BY created_at DESC').bind(owner),env.DB.prepare('SELECT id,collection_id AS collectionId,summary,revision,updated_at AS updatedAt FROM games WHERE owner = ? ORDER BY updated_at DESC').bind(owner)]);return json({collections:results[0].results,games:results[1].results.map(g=>({...g,...JSON.parse(g.summary),summary:undefined}))});}
if(request.method==='POST'&&url.pathname==='/api/collections'){const b=await request.json();if(!cleanText(b.id,100)||!cleanText(b.name,80)||!cleanText(b.teamName,60))return json({error:'Enter a collection name and your team name.'},400);const existing=await env.DB.prepare('SELECT id FROM collections WHERE owner = ? AND lower(name) = lower(?)').bind(owner,b.name.trim()).first();if(existing&&existing.id!==b.id)return json({error:'A collection with that name already exists.'},409);const c={id:b.id,name:b.name.trim(),teamName:b.teamName.trim(),createdAt:new Date().toISOString()};await env.DB.prepare('INSERT INTO collections(owner,id,name,team_name,created_at) VALUES (?,?,?,?,?) ON CONFLICT(owner,id) DO NOTHING').bind(owner,c.id,c.name,c.teamName,c.createdAt).run();return json(c,201);}
const match=url.pathname.match(/^\/api\/games\/([a-zA-Z0-9_-]{1,100})$/);if(match){const id=match[1];if(request.method==='GET'){const row=await env.DB.prepare('SELECT payload,revision FROM games WHERE owner = ? AND id = ?').bind(owner,id).first();return row?json({game:JSON.parse(row.payload),revision:row.revision}):json({error:'Game not found.'},404);}
if(request.method==='PUT'){if(Number(request.headers.get('content-length'))>4000000)return json({error:'Game is too large to save. Export a backup.'},413);const raw=await request.text();if(raw.length>4000000)return json({error:'Game is too large to save. Export a backup.'},413);const b=JSON.parse(raw),s=validGame(b.game);if(s.id!==id||!Number.isInteger(b.revision)||b.revision<0)return json({error:'Invalid game revision.'},400);const collectionId=s.meta?.collectionId||null;if(collectionId){const c=await env.DB.prepare('SELECT id FROM collections WHERE owner = ? AND id = ?').bind(owner,collectionId).first();if(!c)return json({error:'Choose one of your collections.'},400);}delete s.report;delete s.cloudRevision;const d=engine.derive(s),summary={home:d.settings.home,opponent:d.settings.away,date:s.meta?.date||null,startTime:s.meta?.startTime||null,status:d.clock.final?'final':d.clock.started?'in-progress':'scheduled',score:d.score};const payload=JSON.stringify(s),updatedAt=new Date().toISOString();let row;if(b.revision===0){row=await env.DB.prepare('INSERT INTO games(owner,id,collection_id,payload,summary,revision,updated_at) VALUES (?,?,?,?,?,1,?) ON CONFLICT(owner,id) DO NOTHING RETURNING revision').bind(owner,id,collectionId,payload,JSON.stringify(summary),updatedAt).first();}else{row=await env.DB.prepare('UPDATE games SET collection_id = ?, payload = ?, summary = ?, revision = revision + 1, updated_at = ? WHERE owner = ? AND id = ? AND revision = ? RETURNING revision').bind(collectionId,payload,JSON.stringify(summary),updatedAt,owner,id,b.revision).first();}if(!row)return json({error:'This game changed on another device. Export your local backup, then reopen the saved game before continuing.'},409);return json({revision:row.revision,summary:{id,collectionId,...summary,updatedAt}});}}
return json({error:'Not found.'},404);
}catch(e){console.error('Courtside API',e.message);return json({error:e.message?.includes('Invalid')||e.message?.startsWith('Use ')?e.message:'Could not save or load games. Your local game has been kept.'},e.message?.includes('Invalid')?400:503);}}};
